### ISSUE TITLE
Infinite portal jump

### ISSUE THREAD

**Issue by Xyfranium** [Modding-Legacy/Aether-Legacy#118]
The travel time between the Aether and Overworld is practically nothing. As a result, the player gets stuck in an infinite loop between portals. 

Aether Legacy version 1.3.1

**Comment by 115kino** [comment]
Already fixed in v1.4 as stated in previous issues

**Comment by Draconus80** [comment]
This still happens in Minecraft 1.11.2, after downloading the mod from here: http://www.mc-mod.net/aether-legacy-mod/ started a fresh world and was fine the first time using the portal then just keep getting stuck in a loop with the only way out is for a moderator to time a tp command just right to retrieve the player that's stuck!
