### ISSUE TITLE
Advancements cause crashes on Multiplayer.

### ISSUE THREAD

**Issue by Flashwar** [Modding-Legacy/Aether-Legacy#259]
https://pastebin.com/yZSpwqcT

Forge: 14.23.1.2569
Aether I: 1.01

**Comment by KingPhygieBoo** [comment]
Try updating to the latest forge.

**Comment by Lachney** [comment]
Also try updating to the latest version of Aether Legacy. We pushed out some more fixes. Your crash is something to so with advancements on 1.12. Try it out!
https://minecraft.curseforge.com/projects/aether-legacy/files

**Comment by MissPotato** [comment]
We are also experiencing this crash, currently running v1.0.1 which is the newest version of aether for 1.12.2 on the curseforge.com as of writing. However, updating forge to version 2582 causes all achievements to just disappear until you unlock one from that tab. :/

**Comment by KingPhygieBoo** [comment]
That's exactly what's supposed to happen

**Comment by MissPotato** [comment]
Is that vanilla behavior? Because no advancements at all are displaying. Not even base game.

**Comment by KingPhygieBoo** [comment]
Could you give me a screenshot?

**Comment by MissPotato** [comment]
https://i.imgur.com/PVCiNbm.png

I don't really get it either.

**Comment by MissPotato** [comment]
It's a bug related to just forge. I created an instance with just forge installed and tested. I'll report it to them!

**Comment by HorizonsMC** [comment]
I don't get a crash, instead I just get an error and the player DCs from the server sometimes. Wasn't happening before v1.0.1. Maybe SpongeForge is doing something that prevents the crash from happening idk.

https://pastebin.com/aEsrycwL

**Comment by Lachney** [comment]
Very interesting; at least updating Forge is preventing a crash however we'll hope that advancements issue is fixed if it is Forge... we'll look into it still ourselves. Thank you so much everyone.

@HorizonsMC It could be that SpongeForge is using Forge 2555 and not the latest at this time, we'll hope for an update soon! Thank you for sharing your log! 😌

**Comment by Oxosorrel** [comment]
I got this error as well. I updated both client and server to the current build of forge 2582 still crashes the server. I even turned off the announce achievements flag for the server.

Is AetherAdvancementHandler calling to display something on the sever side? Is sever code trying to do something that only the client should do? While I don't code forge, it looks like the server is trying to call DisplayInfo.func_192298_b() which doesn't exist on the sever side of things.  

java.lang.NoSuchMethodError: net.minecraft.advancements.DisplayInfo.func_192298_b()Lnet/minecraft/item/ItemStack;
	at com.legacy.aether.player.AetherAdvancementHandler.onAchievementGet(AetherAdvancementHandler.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_917_AetherAdvancementHandler_onAchievementGet_AdvancementEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1387)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:221)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:158)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192208_a(SourceFile:69)
	at net.minecraft.entity.player.EntityPlayerMP.func_71111_a(EntityPlayerMP.java:972)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:641)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MissPotato** [comment]
We are now having this issue again, as well. It seems to of only been fixed in single player. While multiplayer crashes.

**Comment by Oxosorrel** [comment]
@Lachney Can  we get this reopened, while updating forge fixes this for single player, Aether still crashes out a server when anyone in multiplayer earns any achievement.

**Comment by Flashwar** [comment]
I think most people are using toast control, that's maybe a reason why not the client crash, but the server

**Comment by HorizonsMC** [comment]
I am not using Toast Control and never used it and I still get the server disconnection. I do use Quark's unlock all recipes and Better Advancements.

**Comment by MissPotato** [comment]
I don't even know what Toast Control is...

**Comment by Darkmega18** [comment]
Very well, I'll try a forge update, provided forge doesn't explode all my other things due to glitchy changes in it's later versions that made me get paranoid and hang back on the version I was using in my logs from the other thread: #262

**Comment by Darkmega18** [comment]
alright, testing with forge 1.12.2 - 14.23.1.2583 on my pack.

The issue is mitigated slightly. It disconnects me from the server, and the server doesn't immediately die and I can just reconnect. But the issue does still occur. as I just got the stone age advancement and it popped me out from an internal sever error.

it also threw this into the multicraft console, but it's upside down cause of how said console puts it's stuff out and it also cut off some amount of lines of it near the end:

02.01 07:24:53 [Server] User Authenticator #3/INFO UUID of player Darkmega18 is de6097d6-918d-45c7-9d04-b931a056cdb0 02.01 07:24:49 [Server] Server thread/INFO [FML]: Unloading dimension 42 02.01 07:24:29 [Disconnect] User Darkmega18 has disconnected, reason: unknown 02.01 07:24:29 [Multicraft] Skipped 39 lines due to rate limit (30/s) 02.01 07:24:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151] 02.01 07:24:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?] 02.01 07:24:08 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571) [aed.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600) [aed.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:407) [acl.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71001_a(EntityPlayerMP.java:732) [oq.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.inventory.Container.func_75142_b(Container.java:91) [afr.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71111_a(EntityPlayerMP.java:972) [oq.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192208_a(SourceFile:69) [al.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:158) [al$a.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31) [p$a.class:?] 02.01 07:24:08 [Server] INFO at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:221) [np.class:?] 02.01 07:24:08 [Server] INFO at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1387) [ForgeHooks.class:?] 02.01 07:24:08 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?] 02.01 07:24:08 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] 02.01 07:24:08 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1355_AetherAdvancementHandler_onAchievementGet_AdvancementEvent.invoke(.dynamic) ~[?:?] 02.01 07:24:08 [Server] INFO at com.legacy.aether.player.AetherAdvancementHandler.onAchievementGet(AetherAdvancementHandler.java:23) ~[AetherAdvancementHandler.class:?] 02.01 07:24:08 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.advancements.DisplayInfo.func_192298_b()Lnet/minecraft/item/ItemStack; 02.01 07:24:08 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.AdvancementEvent@4ef49409:

**Comment by Darkmega18** [comment]
oh snap. there it goes. I got the pick up iron advancement that time, and the server still popped and kicked my client back to server menu. Here's the log again.
[crash-2018-01-02_08.07.07-server.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/1597578/crash-2018-01-02_08.07.07-server.txt)

**Comment by MissPotato** [comment]
We ran "/gamerule announceAdvancments 0" and so far no advancements have caused a crash. It seems to be related to the chat event that is fired, though for some reason only affect's the person who the event is fired for.

**Comment by Darkmega18** [comment]
thats a thing? Well alrighty then.

**Comment by MissPotato** [comment]
It only seems to negate the problem some, item certain advancements still crash the server. Like, reflecting the Ghast's fireball. And if you run /advancements grant everything <name> or however the syntax is, it errors out.

**Comment by 115kino** [comment]
It's a hacky fix but it is one of the few workarounds I can find.
