### ISSUE TITLE
Potential issues with overriding the default player inventory

### ISSUE THREAD

**Issue by BBoldt** [Modding-Legacy/Aether-Legacy#90]
I just think you should have a special inventory tab for the special aether stuff, like tinkers' construct and galacticraft did in 1.7.10, otherwise it could potentially conflict with other mods messing with the default inventory.

**Comment by DeGariless** [comment]
Here here! I had to remove Quark's "dump items in chest" button from the player UI.

**Comment by 115kino** [comment]
The Aether inventory will be kept overriding the regular inventory. There are measures in place to ensure other mods that add things to the regular inventory have no conflicts. Compatibility with quark is being worked on.

![qhlg4of 1](https://cloud.githubusercontent.com/assets/1691075/23922862/92c4b608-08da-11e7-91d4-2fa2d3b3e576.jpg)
`

**Comment by BBoldt** [comment]
Okay, as long as everything works okay.

I have an idea though, how about a little button that looks like an arrow that swaps between the two inventories? Similar to the buttons used for baubles or cosmetic inventory. You could throw an arrow right here:
![](http://i.imgur.com/QoLFAfd.png)
It could even be a config option that is disabled by default.

I just think it would look a lot cleaner when aether is being used with a bunch of other mods.

**Comment by BBoldt** [comment]
Related: https://github.com/Vazkii/Quark/issues/297

**Comment by 115kino** [comment]
Fixed the issue in v1.4.
![0ebsg2f 1](https://cloud.githubusercontent.com/assets/1691075/23929116/2eeffff0-08fa-11e7-9ed8-2360590527bf.png)

**Comment by DeGariless** [comment]
Still an issue when the mod "inventory tweaks" is removed.
http://i.imgur.com/20IdH7N.png
